window.__LL_PLUGIN_CONSTANTS__ = {
  CASHFLOW_PLUGIN_ID: "cashflow-game",
  HARDWARE_INSPECTOR_PLUGIN_ID: "hardware-inspector",
  CLIPBOARD_WORKBENCH_PLUGIN_ID: "clipboard-workbench",
  LITESNAP_PLUGIN_ID: "litesnap",
  WEBTOOLS_PASSWORD_PLUGIN_ID: "webtools-password",
  WEBTOOLS_JSON_PLUGIN_ID: "webtools-json",
  WEBTOOLS_JSON_SCHEMA_PLUGIN_ID: "webtools-json-schema",
  WEBTOOLS_DATA_MASK_PLUGIN_ID: "webtools-data-mask",
  WEBTOOLS_URL_PLUGIN_ID: "webtools-url-parse",
  WEBTOOLS_DIFF_PLUGIN_ID: "webtools-diff",
  WEBTOOLS_TIMESTAMP_PLUGIN_ID: "webtools-timestamp",
  WEBTOOLS_TRANSLATE_PLUGIN_ID: "webtools-translate",
  DICTIONARY_PLUGIN_ID: "dictionary",
  WEBTOOLS_REGEX_PLUGIN_ID: "webtools-regex",
  WEBTOOLS_CRON_PLUGIN_ID: "webtools-cron",
  WEBTOOLS_CRYPTO_PLUGIN_ID: "webtools-crypto",
  WEBTOOLS_JWT_PLUGIN_ID: "webtools-jwt",
  WEBTOOLS_STRINGS_PLUGIN_ID: "webtools-strings",
  WEBTOOLS_COLORS_PLUGIN_ID: "webtools-colors",
  WEBTOOLS_IMAGE_BASE64_PLUGIN_ID: "webtools-image-base64",
  WEBTOOLS_IMAGE_PROMPT_PLUGIN_ID: "webtools-image-prompt",
  WEBTOOLS_CONFIG_PLUGIN_ID: "webtools-config-convert",
  WEBTOOLS_SQL_PLUGIN_ID: "webtools-sql-format",
  WEBTOOLS_UNIT_PLUGIN_ID: "webtools-unit-convert",
  WEBTOOLS_FILE_HASH_PLUGIN_ID: "webtools-file-hash",
  WEBTOOLS_PORT_HELPER_PLUGIN_ID: "webtools-port-helper",
  WEBTOOLS_QRCODE_PLUGIN_ID: "webtools-qrcode",
  WEBTOOLS_MARKDOWN_PLUGIN_ID: "webtools-markdown",
  WEBTOOLS_UA_PLUGIN_ID: "webtools-ua",
  WEBTOOLS_API_PLUGIN_ID: "webtools-api-client",
  WEBTOOLS_HTTP_MOCK_PLUGIN_ID: "webtools-http-mock",
  CODEAGENT_SWITCH_PLUGIN_ID: "codeagent-switch",
  DEFAULT_VISIBLE_PLUGIN_IDS: [
    "cashflow-game",
    "hardware-inspector",
    "clipboard-workbench",
    "litesnap",
    "webtools-password",
    "webtools-cron",
    "webtools-json",
    "webtools-json-schema",
    "webtools-data-mask",
    "webtools-crypto",
    "webtools-jwt",
    "webtools-timestamp",
    "webtools-translate",
    "dictionary",
    "webtools-strings",
    "webtools-colors",
    "webtools-diff",
    "webtools-http-mock",
    "webtools-image-base64",
    "webtools-image-prompt",
    "webtools-config-convert",
    "webtools-sql-format",
    "webtools-unit-convert",
    "webtools-file-hash",
    "webtools-port-helper",
    "webtools-regex",
    "webtools-url-parse",
    "webtools-qrcode",
    "webtools-markdown",
    "webtools-ua",
    "webtools-api-client",
    "codeagent-switch"
  ]
};
